import fs from 'node:fs'
import path from 'node:path'

// Server-only. Returns all images for a project by looking up the pre-built
// gallery-manifest.json (generated by scripts/build-gallery-manifest.mjs during
// prebuild). Using a static manifest instead of fs.readdirSync prevents Next.js
// from tracing all 1.7GB of public/images into the serverless function bundle.

let _manifest: Record<string, string[]> | null = null

function getManifest(): Record<string, string[]> {
  if (_manifest) return _manifest
  const manifestPath = path.join(process.cwd(), 'public', 'gallery-manifest.json')
  try {
    _manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'))
  } catch {
    _manifest = {}
  }
  return _manifest!
}

// A gallery image with the intrinsic dimensions next/image needs to reserve
// exact space in the variable-height masonry (no layout shift).
export interface GalleryImage {
  src: string
  w: number
  h: number
}

// Fallback ratio (3:2) for any image missing from the dimensions map — keeps
// next/image happy; the real files are almost always present.
const FALLBACK_DIM: [number, number] = [1200, 800]

let _dimensions: Record<string, [number, number]> | null = null

function getDimensions(): Record<string, [number, number]> {
  if (_dimensions) return _dimensions
  const dimPath = path.join(process.cwd(), 'public', 'gallery-dimensions.json')
  try {
    _dimensions = JSON.parse(fs.readFileSync(dimPath, 'utf8'))
  } catch {
    _dimensions = {}
  }
  return _dimensions!
}

// Server-only. Enrich a list of encoded image URLs with intrinsic dimensions so
// they can be handed to next/image. Called from the (server-rendered) case-study
// page, so the dimensions JSON is never shipped to the client.
export function withDimensions(images: string[]): GalleryImage[] {
  const dims = getDimensions()
  return images.map((src) => {
    const [w, h] = dims[src] ?? FALLBACK_DIM
    return { src, w, h }
  })
}

export function getColorGroups(imagePath: string): { label: string; images: string[] }[] {
  const decoded = decodeURIComponent(imagePath)
  const relDir = path.dirname(decoded).replace(/^\/+/, '')
  const manifest = getManifest()
  const prefix = relDir + '/'
  return Object.entries(manifest)
    .filter(([key]) => key.startsWith(prefix))
    .map(([key, images]) => ({ label: key.slice(prefix.length), images }))
    .sort((a, b) => a.label.localeCompare(b.label))
}

export function getGallery(imagePath: string): string[] {
  const decoded = decodeURIComponent(imagePath)
  const relDir = path.dirname(decoded).replace(/^\/+/, '') // e.g. images/Automotive/GLE-450
  const manifest = getManifest()
  const images = manifest[relDir]
  return images && images.length ? images : [imagePath]
}

/**
 * Hand-picked frames for the homepage sticky gallery, in render order. The
 * StickyGallery component slices this list into columns:
 *   - frames 0–2  → CENTRE column (the pinned trio)
 *   - frames 3–7  → LEFT column (scrolls)
 *   - frames 8–12 → RIGHT column (scrolls)
 * so 13 frames are needed. To swap a photo, just replace a path below with any
 * file under /public/images — spaces are fine, no need to URL-encode (that
 * happens in getLookbookImages). Reorder freely; the comments only mark which
 * slot each frame lands in.
 */
const LOOKBOOK_FRAMES = [
  // ── Centre column (pinned) ──────────────────────────────
  '/images/Fashion/GLITCH GOODS/GLITCH CLUB_outdoor/Glitch_outdoor-002.jpg',
  '/images/Automotive/GLE-450/GLE450_car-001.JPG',
  '/images/Childs/FAshion/Baby gang/BabyGang_fashion-001.jpg',
  // ── Left column (scrolls) ───────────────────────────────
  '/images/Events/Bnghaty event/Bnghaty_koptan-001.jpg',
  '/images/Fashion/Girl bag/GirlBag_product-001.jpg',
  '/images/Eicons_construction/Eicons_landscape-001.jpg',
  '/images/Automotive/koptan jetta/hero jetta.JPG',
  '/images/Fashion/GLITCH GOODS/GLITCH CLUB_outdoor/Glitch_outdoor-003.jpg',
  // ── Right column (scrolls) ──────────────────────────────
  '/images/Automotive/GLE-450/GLE450_car-002.JPG',
  '/images/Childs/FAshion/Baby gang/BabyGang_fashion-002.jpg',
  '/images/Events/Bnghaty event/Bnghaty_koptan-002.jpg',
  '/images/Fashion/Girl bag/GirlBag_product-002.jpg',
  '/images/Eicons_construction/Eicons_landscape-002.jpg',
]

/**
 * Server-only. Returns the hand-picked lookbook frames, URL-encoded and
 * enriched with intrinsic dimensions for next/image. Order is preserved so the
 * list above maps directly onto the gallery's column layout.
 */
export function getLookbookImages(): GalleryImage[] {
  return withDimensions(LOOKBOOK_FRAMES.map((p) => encodeURI(p)))
}
