import fs from 'node:fs'
import path from 'node:path'

// Server-only. Returns all images for a project by looking up the pre-built
// gallery-manifest.json (generated by scripts/build-gallery-manifest.mjs during
// prebuild). Using a static manifest instead of fs.readdirSync prevents Next.js
// from tracing all 1.7GB of public/images into the serverless function bundle.

let _manifest: Record<string, string[]> | null = null

function getManifest(): Record<string, string[]> {
  if (_manifest) return _manifest
  const manifestPath = path.join(process.cwd(), 'public', 'gallery-manifest.json')
  try {
    _manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'))
  } catch {
    _manifest = {}
  }
  return _manifest!
}

export function getGallery(imagePath: string): string[] {
  const decoded = decodeURIComponent(imagePath)
  const relDir = path.dirname(decoded).replace(/^\/+/, '') // e.g. images/Automotive/GLE-450
  const manifest = getManifest()
  const images = manifest[relDir]
  return images && images.length ? images : [imagePath]
}
